name: second workflow
env: 
  WORKFLOW_VAR: "This variable is declared at the workflow level"
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This is a job variable"
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"

